"""Cleaning rules for transcript prose.

Everything here implements report §1.1 (strip harness-injected blocks from user
turns) and §7 / §11.5 (trim invariant template lines, but never drop the
templated message itself).

The regexes are reproduced from report Appendix B.2 deliberately: the measured
numbers were taken with these, so changing them changes the corpus the study
was run on.
"""

from __future__ import annotations

import re

SYSREM = re.compile(r"<system-reminder>.*?</system-reminder>", re.S)
CMD_BLOCK = re.compile(
    r"<(command-name|command-message|command-args|local-command-stdout|local-command-stderr"
    r"|bash-input|bash-stdout|bash-stderr)>.*?</\1>",
    re.S,
)
INJECTED = re.compile(
    r"<task-notification>.*?</task-notification>"
    r"|\[Request interrupted by user[^\]]*\]"
    r"|\[SYSTEM NOTIFICATION - NOT USER INPUT\]",
    re.S,
)
CAVEAT = "Caveat: The messages below were generated by the user while running local commands"

# An unterminated opener (the transcript was truncated mid-block, or the closing
# tag never arrived) would otherwise leak the whole rest of the turn.
_UNCLOSED = re.compile(
    r"<(?:system-reminder|task-notification|command-name|command-message|command-args"
    r"|local-command-stdout|local-command-stderr|bash-input|bash-stdout|bash-stderr)>"
    r"(?![\s\S]*?</)[\s\S]*$",
    re.S,
)

_BLANKS = re.compile(r"\n{3,}")
_TRAILING_WS = re.compile(r"[ \t]+\n")


def strip_injected(text: str) -> str:
    """Remove harness-injected machinery from a message's text (§1.1).

    A message that is nothing but machinery comes back as the empty string; the
    caller drops it.
    """
    if not text:
        return ""
    prev = None
    # Blocks nest in practice (a system-reminder inside a command echo), so
    # iterate to a fixed point rather than assuming one pass is enough.
    while prev != text:
        prev = text
        text = SYSREM.sub("", text)
        text = CMD_BLOCK.sub("", text)
        text = INJECTED.sub("", text)
    text = _UNCLOSED.sub("", text)
    text = _strip_caveat(text)
    return normalise_ws(text)


def _strip_caveat(text: str) -> str:
    """Drop the local-command caveat paragraph the harness prepends."""
    i = text.find(CAVEAT)
    while i != -1:
        end = text.find("\n\n", i)
        text = text[:i] + ("" if end == -1 else text[end + 2 :])
        i = text.find(CAVEAT)
    return text


def normalise_ws(text: str) -> str:
    text = _TRAILING_WS.sub("\n", text)
    text = _BLANKS.sub("\n\n", text)
    return text.strip()


def candidate_lines(text: str, min_len: int = 40) -> set[str]:
    """Lines long enough to be worth counting as possible template boilerplate.

    Short lines (`---`, `## Rules`) are excluded: they are cheap to index and
    frequency alone does not make them boilerplate.
    """
    out = set()
    for line in text.splitlines():
        line = line.rstrip()
        if len(line.strip()) >= min_len:
            out.add(line.strip())
    return out


def trim_boilerplate(text: str, boilerplate: frozenset[str] | set[str]) -> str:
    """Remove invariant template lines, keeping the message (§7, §11.5).

    Deleting the templated *messages* measurably hurts retrieval (family T
    collapses, 0.943 -> 0.821) because the task body inside a launch brief is
    the best summary of that session that exists. Deleting only the invariant
    *lines* is free: identical MACRO scores, ~4% fewer characters.
    """
    if not boilerplate or not text:
        return text
    kept = [ln for ln in text.splitlines() if ln.strip() not in boilerplate]
    return normalise_ws("\n".join(kept))
